### ISSUE TITLE
Error when using AutoQASM with Braket `@hybrid_job` decorator

### ISSUE THREAD

**Issue by yitchen-tim** [amazon-braket/autoqasm#6]
## Summary

AutoQASM programs cannot be run when used inside the [Braket `@hybrid_job` decorator](https://docs.aws.amazon.com/braket/latest/developerguide/braket-hybrid-job-decorator.html#create-hybrid-job-from-local-python-code).

The problem is that `cloudpickle`, on which the `@hybrid_job` decorator is built, does not include the source code of functions that are called or included in the decorated function. The fix is to manually ensure that the source code of the AutoQASM functions is included and can be appropriately retrieved when running inside the hybrid job container.

There is previous prototype PR https://github.com/amazon-braket/amazon-braket-sdk-python/pull/855, targeting the old feature branch in the Braket SDK repo, which fixes this problem. We will want to manually port the changes in that PR over to this repo. But rather than modifying the Braket SDK directly, we should adapt that PR and create a new AutoQASM-specific decorator, e.g. `@aq.hybrid_job`, which extends the Braket functionality with this new behavior.

## Repro Steps

To reproduce the error, run the following code.  
**Note:** [Docker](https://docs.docker.com/get-docker/) must be installed and running locally in order for `@hybrid_job` to work with `local=True`.

```
from braket.jobs import hybrid_job
from braket.devices import Devices

import autoqasm as aq
from autoqasm.instructions import h, cnot

@hybrid_job(
    device=Devices.Amazon.SV1,
    dependencies=["git+https://github.com/amazon-braket/autoqasm.git#egg=autoqasm"],
    local=True
) 
def bell_circuit_job():
    @aq.main
    def bell_circuit():
        h(0)
        cnot(0, 1)

    aq_program = bell_circuit()
    print(aq_program.build().to_ir())

bell_circuit_job()
```

## Expected Result

Job should complete successfully.

## Actual Result

Executing this code in a jupyter notebook causes pyct parsing error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ml/code/braket_container.py", line 267, in wrapped_customer_code
    raise e
  File "/opt/ml/code/braket_container.py", line 258, in wrapped_customer_code
    return customer_method(**kwargs)
  File "/opt/braket/code/customer_code/extracted/decorator_job_qrd6a_fa/entry_point.py", line 72, in bell_circuit_job
    result = recovered()
  File "/var/folders/53/q_0l5g7j7h7fmq6hjstpwl1m0000gs/T/ipykernel_73151/1483909699.py", line 24, in bell_circuit_job
    from pathlib import Path
  File "/usr/local/lib/python3.10/site-packages/autoqasm/api.py", line 162, in _wrapper
    return converter_callback(f, options, args, kwargs, **converter_args)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/api.py", line 207, in _convert_main
    aq_transpiler.converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/transpiler/transpiler.py", line 241, in converted_call
    raise exc
  File "/usr/local/lib/python3.10/site-packages/autoqasm/transpiler/transpiler.py", line 296, in _try_convert_actual
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/transpiler/transpiler.py", line 169, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/transpiler.py", line 282, in transform
    return self.transform_function(obj, user_context)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/transpiler.py", line 466, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/transpiler.py", line 342, in transform_function
    node, source = parser.parse_entity(fn, future_features=future_features)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/parser.py", line 164, in parse_entity
    return parse(source, preamble_len=len(future_features)), source
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/parser.py", line 341, in parse
    raise ValueError('expected exactly one node, got 
{}
'.format(nodes))
```

Executing this code in terminal causes pyct inaccessible source code error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ml/code/braket_container.py", line 267, in wrapped_customer_code
    raise e
  File "/opt/ml/code/braket_container.py", line 258, in wrapped_customer_code
    return customer_method(**kwargs)
  File "/opt/braket/code/customer_code/extracted/decorator_job_4f4vdbac/entry_point.py", line 72, in bell_circuit_job
    result = recovered()
  File "<stdin>", line 7, in bell_circuit_job
  File "/usr/local/lib/python3.10/site-packages/autoqasm/api.py", line 162, in _wrapper
    return converter_callback(f, options, args, kwargs, **converter_args)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/api.py", line 207, in _convert_main
    aq_transpiler.converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/transpiler/transpiler.py", line 241, in converted_call
    raise exc
  File "/usr/local/lib/python3.10/site-packages/autoqasm/transpiler/transpiler.py", line 296, in _try_convert_actual
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/transpiler/transpiler.py", line 169, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/transpiler.py", line 282, in transform
    return self.transform_function(obj, user_context)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/transpiler.py", line 466, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/transpiler.py", line 342, in transform_function
    node, source = parser.parse_entity(fn, future_features=future_features)
  File "/usr/local/lib/python3.10/site-packages/autoqasm/autograph/pyct/parser.py", line 150, in parse_entity
    raise errors.InaccessibleSourceCodeError(
autoqasm.autograph.pyct.errors.InaccessibleSourceCodeError: Unable to locate the source code of <function bell_circuit at 0x402da8ad40>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code.
```

**Comment by rmshaffer** [comment]
Closing the original PR https://github.com/amazon-braket/amazon-braket-sdk-python/pull/855, which is targeting the old feature branch in the Braket SDK repo.

See this comment for a description of how we should proceed when opening a PR targeted at this repo:
https://github.com/amazon-braket/amazon-braket-sdk-python/pull/855#issuecomment-2077834673
